name: Build and deploy app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    environment:
      name: testing

    env:
      MONGODB_URL: mongodb://127.0.0.1:27017/node-boilerplate
      JWT_SECRET: thisisasamplesecret
      JWT_ACCESS_EXPIRATION_MINUTES: 30
      JWT_REFRESH_EXPIRATION_DAYS: 30
      JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
      JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: yarn docker:test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.test.yml" down
